/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Model.HoaDon;
import Model.HoaDonChiTiet;
import Repository.HoaDonRepo;
import Repository.HoaDonChiTietRepo;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author GIGABYTE
 */
public class HoaDon_View extends javax.swing.JInternalFrame {

    /**
     * Creates new form BanHang_View
     */
    HoaDonRepo repo = new HoaDonRepo();
    HoaDonChiTietRepo hdctrepo = new HoaDonChiTietRepo();

    DefaultTableModel model = new DefaultTableModel();
    DefaultTableModel model1 = new DefaultTableModel();
    List<HoaDon> listHD = new ArrayList<>();
    List<HoaDonChiTiet> listHDCT = new ArrayList<>();

    public HoaDon_View() {
        initComponents();
        setBorder();
        model = (DefaultTableModel) tblHoaDon.getModel();
        model1 = (DefaultTableModel) tblChiTietHoaDon.getModel();
        fillTable();
//        fillTableHDCT();

    }

    public void fillTable() {
        listHD = repo.getAll();
        int stt = tblHoaDon.getSelectedRow();
        stt+=1;

        model.setRowCount(0);
        for (HoaDon hd : listHD) {
            model.addRow(new Object[]{
                stt+=1,
                hd.getMaHoaDon(),
                hd.getIdNhanVien().getMaNV(),
                hd.getIdKhachHang().getTenKH(),
                hd.getIdKhachHang().getSDT(),
                hd.getNgayTao(),
                hd.getTrangThai(),});
        
        }
    }
    

    public void fillTableHDCT() {
        listHDCT = hdctrepo.getAll();
        model1.setRowCount(0);
        int stt = tblChiTietHoaDon.getSelectedRow();
        stt+=1;
        for (HoaDonChiTiet hdct : listHDCT) {
            model1.addRow(new Object[]{
                               stt+=1,
                hdct.getIdHoaDon().getMaHoaDon(),
                hdct.getIdSanPham().getTenSP(),
                hdct.getIdMauSac().getTenMau(),
                hdct.getIdHang().getTenHang(),
                hdct.getSoLuong(),
                hdct.getThanhTien()
            });
        }
    }

    void loadTableHoaDonCT() {

    }

//    public void searchByTT() {
//        if (rdoTatCa.isSelected()) {
//            list = repo.getAll();
//            model = (DefaultTableModel) tblHoaDon.getModel();
//            showDataTable(list);
//        } else if (rdoTien.isSelected()) {
//            list = repo.getListByHTTT(1);
//            model = (DefaultTableModel) tblHoaDon.getModel();
//            showDataTable(list);
//        } else if (rdoCK.isSelected()) {
//            list = repo.getListByHTTT(0);
//            model = (DefaultTableModel) tblHoaDon.getModel();
//            showDataTable(list);
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtMaTimKiem = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChiTietHoaDon = new javax.swing.JTable();
        timkiem = new javax.swing.JButton();
        CbbTrangThai = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnLoc = new javax.swing.JButton();
        inexcel = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã HĐ", "Mã Nhân Viên", "Tên Khách Hàng", "SDT", "Ngày Tạo", "Trạng Thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        jLabel1.setText("Tìm kiếm");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa Đơn Chi Tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã HD", "Tên SP", "Màu", "Hãng", "SoLuong", "ThanhTien"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblChiTietHoaDon);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );

        timkiem.setText("Tìm Kiếm");
        timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemActionPerformed(evt);
            }
        });

        CbbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất Cả", "Đã Thanh Toán", "Chưa Thanh Toán" }));
        CbbTrangThai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CbbTrangThaiMouseClicked(evt);
            }
        });

        jLabel3.setText("Trạng Thái Hóa Đơn");

        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        inexcel.setText("Xuất Danh Sách");
        inexcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inexcelActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(inexcel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(77, 77, 77)
                .addComponent(txtMaTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLamMoi)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(timkiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(timkiem)
                        .addComponent(txtMaTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLoc)
                        .addComponent(CbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLamMoi)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inexcel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lịch Sử Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Ngày ", "Trạng Thái"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(582, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        // TODO add your handling code here:
                listHD = repo.getAll();
        model.setRowCount(0);
        for (HoaDon hd : listHD) {
        if(CbbTrangThai.getSelectedItem().equals("Đã Thanh Toán")){
            if(hd.getTrangThai().equals("Ðã Thanh Toán")){
                       model.addRow(new Object[]{
                hd.getID(),
                hd.getMaHoaDon(),
                hd.getIdNhanVien().getMaNV(),
                hd.getIdKhachHang().getTenKH(),
                hd.getIdKhachHang().getSDT(),
                hd.getNgayTao(),
                hd.getTrangThai(),});
            }
            
            System.out.println("Lọc ok");
        }        if(CbbTrangThai.getSelectedItem().equals("Chưa Thanh Toán")){
            if(hd.getTrangThai().equals("Chưa Thanh Toán")){
                       model.addRow(new Object[]{
                hd.getID(),
                hd.getMaHoaDon(),
                hd.getIdNhanVien().getMaNV(),
                hd.getIdKhachHang().getTenKH(),
                hd.getIdKhachHang().getSDT(),
                hd.getNgayTao(),
                hd.getTrangThai(),});
            }
            
            System.out.println("Lọc ok");
        }else{
        fillTable();}

        
        }
    }//GEN-LAST:event_btnLocActionPerformed

    private void inexcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inexcelActionPerformed
        // TODO add your handling code here:
        try {
            XSSFWorkbook wordkbook = new XSSFWorkbook();
            XSSFSheet sheet = wordkbook.createSheet("Hóa Đơn");
            
            XSSFRow row = null;
            Cell cell = null;
            row = sheet.createRow(2);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("DANH SACH HOA DON");

            row = sheet.createRow(3);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("STT");

            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("MA HD");

            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("MA NHAN VIEN");

            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("TEN KHACH HANG");

            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("SDT ");

            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("NGAY TAO");

            cell = row.createCell(6, CellType.NUMERIC);
            cell.setCellValue("TRANG THAI");



            listHD = repo.getAll();
            for (int i = 0; i < listHD.size(); i++) {
                //Modelbook book =arr.get(i);
                row = sheet.createRow(4 + i);
                cell = row.createCell(0, CellType.NUMERIC);
                cell.setCellValue(i + 1);

                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue(listHD.get(i).getMaHoaDon());

                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue(listHD.get(i).getIdNhanVien().getMaNV());

                cell = row.createCell(3, CellType.STRING);
                cell.setCellValue(listHD.get(i).getIdKhachHang().getTenKH());

                cell = row.createCell(4, CellType.STRING);
                cell.setCellValue(listHD.get(i).getIdKhachHang().getSDT());

                cell = row.createCell(5, CellType.STRING);
                cell.setCellValue(listHD.get(i).getNgayTao());

                cell = row.createCell(6, CellType.NUMERIC);
                cell.setCellValue(listHD.get(i).getTrangThai());


            }

            File f = new File("D://HoaDon.xlsx");
            try {
                FileOutputStream fis = new FileOutputStream(f);
                wordkbook.write(fis);
                fis.close();
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();

            } catch (IOException ex) {
                ex.printStackTrace();
            }

            JOptionPane.showMessageDialog(this, "in thanh cong D:\\KhuyenMai");

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Loi mo file");
        }

    }//GEN-LAST:event_inexcelActionPerformed

    private void timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemActionPerformed
        // TODO add your handling code here:
                listHD = repo.getAll();
                  model.setRowCount(0);
        for (HoaDon hd : listHD) {
             if(hd.getMaHoaDon().equals(txtMaTimKiem.getText())){
                System.out.println("Tim thấy");
                 model.addRow(new Object[]{
                hd.getID(),
                hd.getMaHoaDon(),
                hd.getIdNhanVien().getMaNV(),
                hd.getIdKhachHang().getTenKH(),
                hd.getIdKhachHang().getSDT(),
                hd.getNgayTao(),
                hd.getTrangThai(),});
             }
        
        }
        
        
        
    }//GEN-LAST:event_timkiemActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        
        listHD = repo.getAll();
        int rowIndex = tblHoaDon.getSelectedRow();
        HoaDon hd = listHD.get(rowIndex);
             listHDCT = hdctrepo.getAll();
        model1.setRowCount(0);
        int stt = tblChiTietHoaDon.getSelectedRow();
        stt+=1;
        for (HoaDonChiTiet hdct : listHDCT) {
            if(hdct.getIdHoaDon().getMaHoaDon().equals(hd.getMaHoaDon())){
            model1.addRow(new Object[]{
                               stt+=1,
                hdct.getIdHoaDon().getMaHoaDon(),
                hdct.getIdSanPham().getTenSP(),
                hdct.getIdMauSac().getTenMau(),
                hdct.getIdHang().getTenHang(),
                hdct.getSoLuong(),
                hdct.getThanhTien()
            });
            }
        }
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        fillTable();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void CbbTrangThaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbbTrangThaiMouseClicked
        // TODO add your handling code here:
                listHD = repo.getAll();
        model.setRowCount(0);
        for (HoaDon hd : listHD) {
        if(CbbTrangThai.getSelectedItem().equals("Đã Thanh Toán")){
            if(hd.getTrangThai().equals("Ðã Thanh Toán")){
                       model.addRow(new Object[]{
                hd.getID(),
                hd.getMaHoaDon(),
                hd.getIdNhanVien().getMaNV(),
                hd.getIdKhachHang().getTenKH(),
                hd.getIdKhachHang().getSDT(),
                hd.getNgayTao(),
                hd.getTrangThai(),});
            }          
        }        if(CbbTrangThai.getSelectedItem().equals("Chưa Thanh Toán")){
            if(hd.getTrangThai().equals("Chưa Thanh Toán")){
                       model.addRow(new Object[]{
                hd.getID(),
                hd.getMaHoaDon(),
                hd.getIdNhanVien().getMaNV(),
                hd.getIdKhachHang().getTenKH(),
                hd.getIdKhachHang().getSDT(),
                hd.getNgayTao(),
                hd.getTrangThai(),});
            }
            
            System.out.println("Lọc ok");
        }else{
        fillTable();}
        }
        
    }//GEN-LAST:event_CbbTrangThaiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbbTrangThai;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton inexcel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable tblChiTietHoaDon;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JButton timkiem;
    private javax.swing.JTextField txtMaTimKiem;
    // End of variables declaration//GEN-END:variables

    private void setBorder() {
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }
}
